/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "w-full",
    "flex",
    "flex-col",
    "items-center",
    "mb-5",
    "text-center",
    "font-semibold",
    "mx-3",
    "gap-5",
    "py-10",
    "rounded-xl",
    "border",
    "border-green-600",
    "bg-green-50/70",
    "p-5",
    "mt-5",
    "inline-block",
    "mt-3",
    "rounded-lg",
    "bg-green-600",
    "px-5",
    "py-3",
    "text-white",
    "hover:bg-green-700",
    "duration-200",
    "grid",
    "md:grid-cols-3",
    "gap-4",
    "mt-4",
    "border-gray-200",
    "bg-white",
    "p-4",
    "shadow-sm",
    "mt-2",
    "mt-10",
    "round_button",
    "grid-cols-1",
    "sm:py-20",
    "border-green-700",
    "py-14",
    "mx-10",
    "underline",
    "space-y-6",
    "text-gray-800",
    "max-w-5xl",
    "mx-auto",
    "px-4",
    "py-6",
    "page-max-width",
    "relative",
    "text-base",
    "header",
    "sticky",
    "top-2",
    "z-40",
    "h-16",
    "my-2",
    "pr-5",
    "justify-between",
    "rounded-full",
    "border-gray-200/50",
    "text-3xl",
    "font-bold",
    "mb-8",
    "bg-indigo-500", "text-indigo-800",
    "absolute",
    "after:absolute",
    "after:content-['']",
    "after:h-3",
    "after:left-0",
    "after:top-full",
    "after:w-full",
    "aria-hidden:true",
    "attachment-large",
    "bg-clip-padding",
    "bg-neutral-700",
    "bg-opacity-70",
    "bg-white",
    "backdrop-blur-sm",
    "backdrop-filter",
    "block",
    "border",
    "border-gray-200",
    "border-gray-200/50",
    "border-gray-600",
    "border-green-600",
    "border-slate-200",
    "break-words",
    "cursor-pointer",
    "deco-none",
    "decoding-async",
    "drop-shadow-md",
    "duration-200",
    "duration-300",
    "eae-hidden-post-id",
    "eae-popup-content",
    "flex",
    "flex-1",
    "flex-col",
    "flex-nowrap",
    "flex-row",
    "font-bold",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-12",
    "grid",
    "group",
    "group-focus-within:pointer-events-auto",
    "group-focus-within:opacity-100",
    "group-focus-within:visible",
    "group-focus-within:translate-y-0",
    "group-hover:pointer-events-auto",
    "group-hover:opacity-100",
    "group-hover:rotate-180",
    "group-hover:visible",
    "group-hover:translate-y-0",
    "h-auto",
    "h-7",
    "h-16",
    "h-40",
    "h-full",
    "header",
    "hidden",
    "hover:bg-slate-100",
    "hover:scale-105",
    "hover:text-emerald-700",
    "hover:text-lime-500",
    "inline-flex",
    "invisible",
    "items-center",
    "items-start",
    "justify-between",
    "justify-footer",
    "justify-max",
    "justify-start",
    "lazyloaded",
    "leading-none",
    "leading-snug",
    "left-0",
    "lg:flex",
    "lg:hidden",
    "list-disc",
    "lucide",
    "lucide-chevron-down",
    "lucide-linkedin",
    "lucide-menu",
    "lucide-x",
    "max-h-full",
    "max-w-5xl",
    "max-w-full",
    "mb-4",
    "mb-8",
    "mb-10",
    "md:flex-nowrap",
    "md:flex-row",
    "md:grid-cols-2",
    "md:w-11/12",
    "md:w-full",
    "min-h-screen",
    "min-w-0",
    "min-w-56",
    "mt-2",
    "mt-3",
    "mt-4",
    "mx-auto",
    "my-2",
    "my-8",
    "object-contain",
    "opacity-0",
    "opacity-75",
    "p-1",
    "p-2",
    "p-6",
    "page-container",
    "page-max-width",
    "pl-5",
    "pl-6",
    "pointer-events-none",
    "pr-5",
    "px-3",
    "px-4",
    "py-2",
    "py-3",
    "py-6",
    "py-8",
    "py-10",
    "py-20",
    "relative",
    "rounded",
    "rounded-2xl",
    "rounded-3xl",
    "rounded-lg",
    "rounded-md",
    "rounded-xl",
    "shadow-md",
    "shadow-sm",
    "shadow-xl",
    "size-4",
    "size-6",
    "sm:gap-12",
    "space-y-2",
    "space-y-4",
    "space-y-6",
    "sticky",
    "text",
    "text-base",
    "text-center",
    "text-emerald-700",
    "text-gray-50",
    "text-gray-100",
    "text-gray-800",
    "text-gold-500",
    "text-lg",
    "text-slate-700",
    "text-sm",
    "text-3xl",
    "top-2",
    "top-full",
    "transition",
    "transition-colors",
    "translate-y-1",
    "underline",
    "w-44",
    "w-60",
    "w-72",
    "w-11/12",
    "w-full",
    "whitespace-normal",
    "wp-image-7282",
    "wp-image-7444",
    "z-40",
    "z-50",
    "mx-auto",
    "max-w-5xl",




    "flex-shrink-0",
    "opacity-100", "opacity-90", "opacity-80", "opacity-70", "opacity-60", "opacity-50", "opacity-40", "opacity-30", "opacity-20", "opacity-10",
    "text-sm", "text-md", "text-lg", "text-xl", "text-2xl", "text-3xl", "text-4xl", "text-5xl", "text-6xl",
    "border",
    "border-gray-200", "bg-white", "shadow-sm", "rounded-lg", "p-4", "mb-4", "text-gray-800", "font-semibold", "text-lg", "mb-2", "text-gray-700", "text-base",
    "text-green-50", "text-green-100", "text-green-200", "text-green-300", "text-green-400", "text-green-500", "text-green-600", "text-green-700", "text-green-800", "text-green-900",
    "w-0", "w-auto", "w-full", "w-1/2", "w-1/3", "w-2/3", "w-1/4", "w-3/4", , "w-1", "w-2", "w-3", "w-4", "w-5", "w-6", "w-8", "w-10", "w-12", "w-14", "w-16", "w-20", "w-24", "w-32", "w-40", "w-48", "w-56", "w-64",
    "mt-1", "mt-2", "mt-3", "mt-4", "mt-5", "mt-6", "mt-8", "mt-10", "mt-12", "mt-14", "mt-16", "mt-20",
    "mx-1", "mx-2", "mx-3", "mx-4", "mx-5", "mx-6", "mx-8", "mx-10", "mx-12", "mx-14", "mx-16", "mx-20",
    "mb-1", "mb-2", "mb-3", "mb-4", "mb-5", "mb-6", "mb-8", "mb-10", "mb-12", "mb-14", "mb-16", "mb-20",
    "mr-1", "mr-2", "mr-3", "mr-4", "mr-5", "mr-6", "mr-8", "mr-10", "mr-12", "mr-14", "mr-16", "mr-20",
    "ml-1", "ml-2", "ml-3", "ml-4", "ml-5", "ml-6", "ml-8", "ml-10", "ml-12", "ml-14", "ml-16", "ml-20",
    "p-1", "p-2", "p-3", "p-4", "p-5", "p-6", "p-8", "p-10", "p-12", "p-14", "p-16", "p-20",
    "px-1", "px-2", "px-3", "px-4", "px-5", "px-6", "px-8", "px-10", "px-12", "px-14", "px-16", "px-20",
    "py-1", "py-2", "py-3", "py-4", "py-5", "py-6", "py-8", "py-10", "py-12", "py-14", "py-16", "py-20",
    "space-y-1", "space-y-2", "space-y-3", "space-y-4", "space-y-5", "space-y-6", "space-y-8", "space-y-10", "space-y-12", "space-y-14", "space-y-16", "space-y-20",
    "grid", "grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4", "grid-cols-5", "grid-cols-6", "grid-cols-8", "grid-cols-10", "grid-cols-12",
    "md:grid-cols-1", "md:grid-cols-2", "md:grid-cols-3", "md:grid-cols-4", "md:grid-cols-5", "md:grid-cols-6", "md:grid-cols-8", "md:grid-cols-10", "md:grid-cols-12",
    "gap-1", "gap-2", "gap-3", "gap-4", "gap-5", "gap-6", "gap-8", "gap-10", "gap-12", "gap-14", "gap-16", "gap-20",
    "w-1", "w-2", "w-3", "w-4", "w-5", "w-6", "w-8", "w-10", "w-12", "w-14", "w-16", "w-20", "w-24", "w-32", "w-40", "w-48", "w-56", "w-64","w-72","w-80","w-96","w-auto","w-full","w-screen",
    "h-1", "h-2", "h-3", "h-4", "h-5", "h-6", "h-8", "h-10", "h-12", "h-14", "h-16", "h-20", "h-24", "h-32", "h-40", "h-48", "h-56", "h-64","h-auto","h-full","h-screen",
    "h-[100px]", "h-[200px]", "h-[300px]", "h-[400px]", "h-[500px]", "h-[600px]", "h-[700px]", "h-[800px]", "h-[900px]", "h-[1000px]",
    "md:w-60", "md:w-72", "md:w-80", "md:w-96", "md:w-auto", "md:w-full", "md:w-screen",
    "md:h-60", "md:h-72", "md:h-80", "md:h-96", "md:h-auto", "md:h-full", "md:h-screen",
 
    "group",
    "relative",
    "flex",
    "flex-col",
    "justify-between",
    "border",
    "border-slate-100",
    "bg-white",
    "p-6",
    "shadow-sm",
    "transition-all",
    "duration-300",
    "hover:-translate-y-1",
    "hover:shadow-md",
    "rounded-2xl",
    "text-slate-800",







    

    "w-full",
    "flex",
    "flex-col",
    "items-center",
    "gap-5",
    "w-full",
    "rounded-lg",
    "bg-gray-900",
    "text-white",
    "p-5",
    "w-full",
    "max-w-4xl",
    "shadow-md",
    "text-2xl",
    "font-bold",
    "mb-4",
    "text-yellow-300",
    "w-full",
    "rounded-lg",
    "bg-blue-50",
    "p-5",
    "w-full",
    "max-w-4xl",
    "flex",
    "gap-5",
    "items-center",
    "flex",
    "flex-col",
    "items-center",
    "relative",
    "text-2xl",
    "font-bold",
    "text-gray-800",
    "text-sm",
    "text-gray-600",
    "absolute",
    "top-0",
    "right-0",
    "transform",
    "translate-x-1/2",
    "-translate-y-1/2",
    "flex",
    "flex-col",
    "items-center",
    "justify-between",
    "gap-2",
    "bg-blue-600",
    "text-white",
    "px-4",
    "py-2",
    "rounded",
    "hover:bg-blue-700",
    "transition-colors",
    "w-full",
    "additional-description",
    "video",
    "video-content-wrapper",
    "terms",
    "benefits",
    "info-benefit-box",
    "buying-info-benefit",
    "mark",
    "mark-green",
    "providers-wrapper",
    "providers",
    "w-full",
    "short-description",

    "mx-auto","w-80","max-w-7xl","px-4","py-8","mb-6","text-2xl","font-bold","text-gray-900","grid","gap-6","sm:grid-cols-2","lg:grid-cols-3","block","rounded-lg","border","border-gray-200","bg-white","p-4","shadow-sm","transition","hover:shadow-md","flex","h-full","flex-col","mb-4","h-40","w-full","rounded-md","object-cover","text-lg","font-semibold","mt-auto","items-center","justify-between","gap-4","gap-2","text-sm","text-gray-600","rounded","bg-blue-600","px-3","py-2","font-medium","text-white","mt-8","list-disc","space-y-2","pl-6",

  ],
  // safelist: [
  //   {
  //     pattern: /.*/, // This forces Tailwind to match and generate everything
  //   },
  // ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
