import FormBuilder from "@/components/formBuilder";


const countries = [
    { "value": "Afghanistan", "label": "Afghanistan" },
    { "value": "Albania", "label": "Albania" },
    { "value": "Algeria", "label": "Algeria" },
    { "value": "American Samoa", "label": "American Samoa" },
    { "value": "Andorra", "label": "Andorra" },
    { "value": "Angola", "label": "Angola" },
    { "value": "Anguilla", "label": "Anguilla" },
    { "value": "Antarctica", "label": "Antarctica" },
    { "value": "Antigua and Barbuda", "label": "Antigua and Barbuda" },
    { "value": "Argentina", "label": "Argentina" },
    { "value": "Armenia", "label": "Armenia" },
    { "value": "Aruba", "label": "Aruba" },
    { "value": "Australia", "label": "Australia" },
    { "value": "Austria", "label": "Austria" },
    { "value": "Azerbaijan", "label": "Azerbaijan" },
    { "value": "Bahamas", "label": "Bahamas" },
    { "value": "Bahrain", "label": "Bahrain" },
    { "value": "Bangladesh", "label": "Bangladesh" },
    { "value": "Barbados", "label": "Barbados" },
    { "value": "Belarus", "label": "Belarus" },
    { "value": "Belgium", "label": "Belgium" },
    { "value": "Belize", "label": "Belize" },
    { "value": "Benin", "label": "Benin" },
    { "value": "Bermuda", "label": "Bermuda" },
    { "value": "Bhutan", "label": "Bhutan" },
    { "value": "Bolivia", "label": "Bolivia" },
    { "value": "Bonaire, Sint Eustatius and Saba", "label": "Bonaire, Sint Eustatius and Saba" },
    { "value": "Bosnia and Herzegovina", "label": "Bosnia and Herzegovina" },
    { "value": "Botswana", "label": "Botswana" },
    { "value": "Bouvet Island", "label": "Bouvet Island" },
    { "value": "Brazil", "label": "Brazil" },
    { "value": "British Indian Ocean Territory", "label": "British Indian Ocean Territory" },
    { "value": "Brunei Darussalam", "label": "Brunei Darussalam" },
    { "value": "Bulgaria", "label": "Bulgaria" },
    { "value": "Burkina Faso", "label": "Burkina Faso" },
    { "value": "Burundi", "label": "Burundi" },
    { "value": "Cambodia", "label": "Cambodia" },
    { "value": "Cameroon", "label": "Cameroon" },
    { "value": "Canada", "label": "Canada" },
    { "value": "Cape Verde", "label": "Cape Verde" },
    { "value": "Cayman Islands", "label": "Cayman Islands" },
    { "value": "Central African Republic", "label": "Central African Republic" },
    { "value": "Chad", "label": "Chad" },
    { "value": "Chile", "label": "Chile" },
    { "value": "China", "label": "China" },
    { "value": "Christmas Island", "label": "Christmas Island" },
    { "value": "Cocos Islands", "label": "Cocos Islands" },
    { "value": "Colombia", "label": "Colombia" },
    { "value": "Comoros", "label": "Comoros" },
    { "value": "Congo, Democratic Republic of the", "label": "Congo, Democratic Republic of the" },
    { "value": "Congo, Republic of the", "label": "Congo, Republic of the" },
    { "value": "Cook Islands", "label": "Cook Islands" },
    { "value": "Costa Rica", "label": "Costa Rica" },
    { "value": "Croatia", "label": "Croatia" },
    { "value": "Cuba", "label": "Cuba" },
    { "value": "Curaçao", "label": "Curaçao" },
    { "value": "Cyprus", "label": "Cyprus" },
    { "value": "Czech Republic", "label": "Czech Republic" },
    { "value": "Côte d'Ivoire", "label": "Côte d'Ivoire" },
    { "value": "Denmark", "label": "Denmark" },
    { "value": "Djibouti", "label": "Djibouti" },
    { "value": "Dominica", "label": "Dominica" },
    { "value": "Dominican Republic", "label": "Dominican Republic" },
    { "value": "Ecuador", "label": "Ecuador" },
    { "value": "Egypt", "label": "Egypt" },
    { "value": "El Salvador", "label": "El Salvador" },
    { "value": "Equatorial Guinea", "label": "Equatorial Guinea" },
    { "value": "Eritrea", "label": "Eritrea" },
    { "value": "Estonia", "label": "Estonia" },
    { "value": "Eswatini (Swaziland)", "label": "Eswatini (Swaziland)" },
    { "value": "Ethiopia", "label": "Ethiopia" },
    { "value": "Falkland Islands", "label": "Falkland Islands" },
    { "value": "Faroe Islands", "label": "Faroe Islands" },
    { "value": "Fiji", "label": "Fiji" },
    { "value": "Finland", "label": "Finland" },
    { "value": "France", "label": "France" },
    { "value": "French Guiana", "label": "French Guiana" },
    { "value": "French Polynesia", "label": "French Polynesia" },
    { "value": "French Southern Territories", "label": "French Southern Territories" },
    { "value": "Gabon", "label": "Gabon" },
    { "value": "Gambia", "label": "Gambia" },
    { "value": "Georgia", "label": "Georgia" },
    { "value": "Germany", "label": "Germany" },
    { "value": "Ghana", "label": "Ghana" },
    { "value": "Gibraltar", "label": "Gibraltar" },
    { "value": "Greece", "label": "Greece" },
    { "value": "Greenland", "label": "Greenland" },
    { "value": "Grenada", "label": "Grenada" },
    { "value": "Guadeloupe", "label": "Guadeloupe" },
    { "value": "Guam", "label": "Guam" },
    { "value": "Guatemala", "label": "Guatemala" },
    { "value": "Guernsey", "label": "Guernsey" },
    { "value": "Guinea", "label": "Guinea" },
    { "value": "Guinea-Bissau", "label": "Guinea-Bissau" },
    { "value": "Guyana", "label": "Guyana" },
    { "value": "Haiti", "label": "Haiti" },
    { "value": "Heard and McDonald Islands", "label": "Heard and McDonald Islands" },
    { "value": "Holy See", "label": "Holy See" },
    { "value": "Honduras", "label": "Honduras" },
    { "value": "Hong Kong", "label": "Hong Kong" },
    { "value": "Hungary", "label": "Hungary" },
    { "value": "Iceland", "label": "Iceland" },
    { "value": "India", "label": "India" },
    { "value": "Indonesia", "label": "Indonesia" },
    { "value": "Iran", "label": "Iran" },
    { "value": "Iraq", "label": "Iraq" },
    { "value": "Ireland", "label": "Ireland" },
    { "value": "Isle of Man", "label": "Isle of Man" },
    { "value": "Israel", "label": "Israel" },
    { "value": "Italy", "label": "Italy" },
    { "value": "Jamaica", "label": "Jamaica" },
    { "value": "Japan", "label": "Japan" },
    { "value": "Jersey", "label": "Jersey" },
    { "value": "Jordan", "label": "Jordan" },
    { "value": "Kazakhstan", "label": "Kazakhstan" },
    { "value": "Kenya", "label": "Kenya" },
    { "value": "Kiribati", "label": "Kiribati" },
    { "value": "Kuwait", "label": "Kuwait" },
    { "value": "Kyrgyzstan", "label": "Kyrgyzstan" },
    { "value": "Lao People's Democratic Republic", "label": "Lao People's Democratic Republic" },
    { "value": "Latvia", "label": "Latvia" },
    { "value": "Lebanon", "label": "Lebanon" },
    { "value": "Lesotho", "label": "Lesotho" },
    { "value": "Liberia", "label": "Liberia" },
    { "value": "Libya", "label": "Libya" },
    { "value": "Liechtenstein", "label": "Liechtenstein" },
    { "value": "Lithuania", "label": "Lithuania" },
    { "value": "Luxembourg", "label": "Luxembourg" },
    { "value": "Macau", "label": "Macau" },
    { "value": "Macedonia", "label": "Macedonia" },
    { "value": "Madagascar", "label": "Madagascar" },
    { "value": "Malawi", "label": "Malawi" },
    { "value": "Malaysia", "label": "Malaysia" },
    { "value": "Maldives", "label": "Maldives" },
    { "value": "Mali", "label": "Mali" },
    { "value": "Malta", "label": "Malta" },
    { "value": "Marshall Islands", "label": "Marshall Islands" },
    { "value": "Martinique", "label": "Martinique" },
    { "value": "Mauritania", "label": "Mauritania" },
    { "value": "Mauritius", "label": "Mauritius" },
    { "value": "Mayotte", "label": "Mayotte" },
    { "value": "Mexico", "label": "Mexico" },
    { "value": "Micronesia", "label": "Micronesia" },
    { "value": "Moldova", "label": "Moldova" },
    { "value": "Monaco", "label": "Monaco" },
    { "value": "Mongolia", "label": "Mongolia" },
    { "value": "Montenegro", "label": "Montenegro" },
    { "value": "Montserrat", "label": "Montserrat" },
    { "value": "Morocco", "label": "Morocco" },
    { "value": "Mozambique", "label": "Mozambique" },
    { "value": "Myanmar", "label": "Myanmar" },
    { "value": "Namibia", "label": "Namibia" },
    { "value": "Nauru", "label": "Nauru" },
    { "value": "Nepal", "label": "Nepal" },
    { "value": "Netherlands", "label": "Netherlands" },
    { "value": "New Caledonia", "label": "New Caledonia" },
    { "value": "New Zealand", "label": "New Zealand" },
    { "value": "Nicaragua", "label": "Nicaragua" },
    { "value": "Niger", "label": "Niger" },
    { "value": "Nigeria", "label": "Nigeria" },
    { "value": "Niue", "label": "Niue" },
    { "value": "Norfolk Island", "label": "Norfolk Island" },
    { "value": "North Korea", "label": "North Korea" },
    { "value": "Northern Mariana Islands", "label": "Northern Mariana Islands" },
    { "value": "Norway", "label": "Norway" },
    { "value": "Oman", "label": "Oman" },
    { "value": "Pakistan", "label": "Pakistan" },
    { "value": "Palau", "label": "Palau" },
    { "value": "Palestine, State of", "label": "Palestine, State of" },
    { "value": "Panama", "label": "Panama" },
    { "value": "Papua New Guinea", "label": "Papua New Guinea" },
    { "value": "Paraguay", "label": "Paraguay" },
    { "value": "Peru", "label": "Peru" },
    { "value": "Philippines", "label": "Philippines" },
    { "value": "Pitcairn", "label": "Pitcairn" },
    { "value": "Poland", "label": "Poland" },
    { "value": "Portugal", "label": "Portugal" },
    { "value": "Puerto Rico", "label": "Puerto Rico" },
    { "value": "Qatar", "label": "Qatar" },
    { "value": "Romania", "label": "Romania" },
    { "value": "Russia", "label": "Russia" },
    { "value": "Rwanda", "label": "Rwanda" },
    { "value": "Réunion", "label": "Réunion" },
    { "value": "Saint Barthélemy", "label": "Saint Barthélemy" },
    { "value": "Saint Helena", "label": "Saint Helena" },
    { "value": "Saint Kitts and Nevis", "label": "Saint Kitts and Nevis" },
    { "value": "Saint Lucia", "label": "Saint Lucia" },
    { "value": "Saint Martin", "label": "Saint Martin" },
    { "value": "Saint Pierre and Miquelon", "label": "Saint Pierre and Miquelon" },
    { "value": "Saint Vincent and the Grenadines", "label": "Saint Vincent and the Grenadines" },
    { "value": "Samoa", "label": "Samoa" },
    { "value": "San Marino", "label": "San Marino" },
    { "value": "Sao Tome and Principe", "label": "Sao Tome and Principe" },
    { "value": "Saudi Arabia", "label": "Saudi Arabia" },
    { "value": "Senegal", "label": "Senegal" },
    { "value": "Serbia", "label": "Serbia" },
    { "value": "Seychelles", "label": "Seychelles" },
    { "value": "Sierra Leone", "label": "Sierra Leone" },
    { "value": "Singapore", "label": "Singapore" },
    { "value": "Sint Maarten", "label": "Sint Maarten" },
    { "value": "Slovakia", "label": "Slovakia" },
    { "value": "Slovenia", "label": "Slovenia" },
    { "value": "Solomon Islands", "label": "Solomon Islands" },
    { "value": "Somalia", "label": "Somalia" },
    { "value": "South Africa", "label": "South Africa" },
    { "value": "South Georgia", "label": "South Georgia" },
    { "value": "South Korea", "label": "South Korea" },
    { "value": "South Sudan", "label": "South Sudan" },
    { "value": "Spain", "label": "Spain" },
    { "value": "Sri Lanka", "label": "Sri Lanka" },
    { "value": "Sudan", "label": "Sudan" },
    { "value": "Suriname", "label": "Suriname" },
    { "value": "Svalbard and Jan Mayen Islands", "label": "Svalbard and Jan Mayen Islands" },
    { "value": "Sweden", "label": "Sweden" },
    { "value": "Switzerland", "label": "Switzerland" },
    { "value": "Syria", "label": "Syria" },
    { "value": "Taiwan", "label": "Taiwan" },
    { "value": "Tajikistan", "label": "Tajikistan" },
    { "value": "Tanzania", "label": "Tanzania" },
    { "value": "Thailand", "label": "Thailand" },
    { "value": "Timor-Leste", "label": "Timor-Leste" },
    { "value": "Togo", "label": "Togo" },
    { "value": "Tokelau", "label": "Tokelau" },
    { "value": "Tonga", "label": "Tonga" },
    { "value": "Trinidad and Tobago", "label": "Trinidad and Tobago" },
    { "value": "Tunisia", "label": "Tunisia" },
    { "value": "Turkey", "label": "Turkey" },
    { "value": "Turkmenistan", "label": "Turkmenistan" },
    { "value": "Turks and Caicos Islands", "label": "Turks and Caicos Islands" },
    { "value": "Tuvalu", "label": "Tuvalu" },
    { "value": "US Minor Outlying Islands", "label": "US Minor Outlying Islands" },
    { "value": "Uganda", "label": "Uganda" },
    { "value": "Ukraine", "label": "Ukraine" },
    { "value": "United Arab Emirates", "label": "United Arab Emirates" },
    { "value": "United Kingdom", "label": "United Kingdom" },
    { "value": "United States", "label": "United States" },
    { "value": "Uruguay", "label": "Uruguay" },
    { "value": "Uzbekistan", "label": "Uzbekistan" },
    { "value": "Vanuatu", "label": "Vanuatu" },
    { "value": "Venezuela", "label": "Venezuela" },
    { "value": "Vietnam", "label": "Vietnam" },
    { "value": "Virgin Islands, British", "label": "Virgin Islands, British" },
    { "value": "Virgin Islands, U.S.", "label": "Virgin Islands, U.S." },
    { "value": "Wallis and Futuna", "label": "Wallis and Futuna" },
    { "value": "Western Sahara", "label": "Western Sahara" },
    { "value": "Yemen", "label": "Yemen" },
    { "value": "Zambia", "label": "Zambia" },
    { "value": "Zimbabwe", "label": "Zimbabwe" },
    { "value": "Åland Islands", "label": "Åland Islands" }
]


export default function HorizonPartnerSearch() {
    return (
        <div className="w-full py-10">
            < FormBuilder
                data={{
                    action: "horizon-partner-search",
                }}
                fields={
                    [

                        // Professional Profile
                        { name: 'organization', label: 'Organization information', type: 'header' },
                        { name: 'organization', label: 'Organization', type: 'text', required: true },
                        {

                            name: 'country',
                            label: 'Country',
                            type: 'select',
                            required: true,
                            options: [
                                { value: '', label: '' },
                                ...countries
                            ]
                        },
                        {

                            name: 'organization_type',
                            label: 'Organization Type',
                            type: 'select',
                            required: true,
                            helperText: "*For more information about the definition SMEs, please visit this link: https://ec.europa.eu/growth/smes/sme-definition_en",
                            options: [
                                { value: 'SME (Small and medium-sized enterprise)', label: 'SME (Small and medium-sized enterprise)' },
                                { value: 'Company (non-SME)', label: 'Company (non-SME)' },
                                { value: 'University / Research', label: 'University / Research' },
                                { value: 'Non-profit', label: 'Non-profit' },
                                { value: 'Public authorities', label: 'Public authorities' },
                            ]
                        },

                        // Personal Information
                        { name: 'contact_person', label: 'Contact Person\'s Information', type: 'header' },
                        { name: 'first_name', label: 'First Name', type: 'text', required: true },
                        { name: 'last_name', label: 'Last Name', type: 'text', required: true },
                        { name: 'email', label: 'Email Address', type: 'email', required: true },
                        { name: 'position', label: 'Position', type: 'text', required: true },
                        { name: 'department', label: 'Department', type: 'text', required: false, helperText: "*If applicable" },

                        { name: 'topics_of_interest', label: 'Topics of Interest', type: 'header' },
                        {
                            name: 'topics_helper',
                            label: `
                        Which Horizon Europe topic/s are you interested in? 
                        Please indicate the topic identifier/s below. For example: HORIZON-CL2-DEMOCRACY-2021-01-01
                        If you're not sure yet, please leave this empty.
                        `,
                            type: 'paragraph'
                        },
                        { name: 'topic_1', label: 'Topic 1', type: 'text', required: true },
                        { name: 'topic_2', label: 'Topic 2', type: 'text', required: true },
                        { name: 'topic_3', label: 'Topic 3', type: 'text', required: true },
                        {

                            name: 'what_role',
                            label: 'What Role',
                            type: 'select',
                            required: true,
                            options: [
                                { value: 'Scientific leading partner', label: 'Scientific leading partner' },
                                { value: 'Partner', label: 'Partner' },

                            ]
                        },
                        {
                            name: 'topics_helper',
                            label: "Please select up to 3 scientific areas that best characterize your expertise*",
                            type: 'paragraph'
                        },
                        {
                            "name": "area_of_expertise_1",
                            "original_name": "input_50",
                            "label": "Area of expertise 1 (mandatory)",
                            "type": "select",
                            "required": true,
                            "options": [
                                { value: '', label: '' },
                                { "value": "PE1 Mathematics", "label": "PE1 Mathematics" },
                                { "value": "PE2 Fundamental Constituents of Matter", "label": "PE2 Fundamental Constituents of Matter" },
                                { "value": "PE3 Condensed Matter Physics", "label": "PE3 Condensed Matter Physics" },
                                { "value": "PE4 Physical and Analytical Chemical Sciences", "label": "PE4 Physical and Analytical Chemical Sciences" },
                                { "value": "PE5 Synthetic Chemistry and Materials", "label": "PE5 Synthetic Chemistry and Materials" },
                                { "value": "PE6 Computer Science and Informatics", "label": "PE6 Computer Science and Informatics" },
                                { "value": "PE7 Systems and Communication Engineering", "label": "PE7 Systems and Communication Engineering" },
                                { "value": "PE8 Products and Processes Engineering", "label": "PE8 Products and Processes Engineering" },
                                { "value": "PE9 Universe Sciences", "label": "PE9 Universe Sciences" },
                                { "value": "PE10 Earth System Science", "label": "PE10 Earth System Science" },
                                { "value": "PE11 Materials Engineering", "label": "PE11 Materials Engineering" },
                                { "value": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions", "label": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions" },
                                { "value": "LS2 Integrative Biology: from Genes and Genomes to Systems", "label": "LS2 Integrative Biology: from Genes and Genomes to Systems" },
                                { "value": "LS3 Cell Biology, Development, Stem Cells and Regeneration", "label": "LS3 Cell Biology, Development, Stem Cells and Regeneration" },
                                { "value": "LS4 Physiology in Health, Disease and Ageing", "label": "LS4 Physiology in Health, Disease and Ageing" },
                                { "value": "LS5 Neuroscience and Disorders of the Nervous System", "label": "LS5 Neuroscience and Disorders of the Nervous System" },
                                { "value": "LS6 Immunity, Infection and Immunotherapy", "label": "LS6 Immunity, Infection and Immunotherapy" },
                                { "value": "LS7 Prevention, Diagnosis and Treatment of Human Diseases", "label": "LS7 Prevention, Diagnosis and Treatment of Human Diseases" },
                                { "value": "LS8 Environmental Biology, Ecology and Evolution", "label": "LS8 Environmental Biology, Ecology and Evolution" },
                                { "value": "LS9 Biotechnology and Biosystems Engineering", "label": "LS9 Biotechnology and Biosystems Engineering" },
                                { "value": "SH1 Individuals, Markets and Organisations", "label": "SH1 Individuals, Markets and Organisations" },
                                { "value": "SH2 Institutions, Governance and Legal Systems", "label": "SH2 Institutions, Governance and Legal Systems" },
                                { "value": "SH3 The Social World and Its Interactions", "label": "SH3 The Social World and Its Interactions" },
                                { "value": "SH4 The Human Mind and Its Complexity", "label": "SH4 The Human Mind and Its Complexity" },
                                { "value": "SH5 Texts and Concepts", "label": "SH5 Texts and Concepts" },
                                { "value": "SH6 The Study of the Human Past", "label": "SH6 The Study of the Human Past" },
                                { "value": "SH7 Human Mobility, Environment, and Space", "label": "SH7 Human Mobility, Environment, and Space" },
                                { "value": "SH8 Studies of Cultures and Arts", "label": "SH8 Studies of Cultures and Arts" }
                            ]
                        },
                        {
                            "name": "area_of_expertise_2",
                            "original_name": "input_52",
                            "label": "Area of expertise 2 (optional)",
                            "type": "select",
                            "required": false,
                            "options": [
                                { value: '', label: '' },
                                { "value": "PE1 Mathematics", "label": "PE1 Mathematics" },
                                { "value": "PE2 Fundamental Constituents of Matter", "label": "PE2 Fundamental Constituents of Matter" },
                                { "value": "PE3 Condensed Matter Physics", "label": "PE3 Condensed Matter Physics" },
                                { "value": "PE4 Physical and Analytical Chemical Sciences", "label": "PE4 Physical and Analytical Chemical Sciences" },
                                { "value": "PE5 Synthetic Chemistry and Materials", "label": "PE5 Synthetic Chemistry and Materials" },
                                { "value": "PE6 Computer Science and Informatics", "label": "PE6 Computer Science and Informatics" },
                                { "value": "PE7 Systems and Communication Engineering", "label": "PE7 Systems and Communication Engineering" },
                                { "value": "PE8 Products and Processes Engineering", "label": "PE8 Products and Processes Engineering" },
                                { "value": "PE9 Universe Sciences", "label": "PE9 Universe Sciences" },
                                { "value": "PE10 Earth System Science", "label": "PE10 Earth System Science" },
                                { "value": "PE11 Materials Engineering", "label": "PE11 Materials Engineering" },
                                { "value": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions", "label": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions" },
                                { "value": "LS2 Integrative Biology: from Genes and Genomes to Systems", "label": "LS2 Integrative Biology: from Genes and Genomes to Systems" },
                                { "value": "LS3 Cell Biology, Development, Stem Cells and Regeneration", "label": "LS3 Cell Biology, Development, Stem Cells and Regeneration" },
                                { "value": "LS4 Physiology in Health, Disease and Ageing", "label": "LS4 Physiology in Health, Disease and Ageing" },
                                { "value": "LS5 Neuroscience and Disorders of the Nervous System", "label": "LS5 Neuroscience and Disorders of the Nervous System" },
                                { "value": "LS6 Immunity, Infection and Immunotherapy", "label": "LS6 Immunity, Infection and Immunotherapy" },
                                { "value": "LS7 Prevention, Diagnosis and Treatment of Human Diseases", "label": "LS7 Prevention, Diagnosis and Treatment of Human Diseases" },
                                { "value": "LS8 Environmental Biology, Ecology and Evolution", "label": "LS8 Environmental Biology, Ecology and Evolution" },
                                { "value": "LS9 Biotechnology and Biosystems Engineering", "label": "LS9 Biotechnology and Biosystems Engineering" },
                                { "value": "SH1 Individuals, Markets and Organisations", "label": "SH1 Individuals, Markets and Organisations" },
                                { "value": "SH2 Institutions, Governance and Legal Systems", "label": "SH2 Institutions, Governance and Legal Systems" },
                                { "value": "SH3 The Social World and Its Interactions", "label": "SH3 The Social World and Its Interactions" },
                                { "value": "SH4 The Human Mind and Its Complexity", "label": "SH4 The Human Mind and Its Complexity" },
                                { "value": "SH5 Texts and Concepts", "label": "SH5 Texts and Concepts" },
                                { "value": "SH6 The Study of the Human Past", "label": "SH6 The Study of the Human Past" },
                                { "value": "SH7 Human Mobility, Environment, and Space", "label": "SH7 Human Mobility, Environment, and Space" },
                                { "value": "SH8 Studies of Cultures and Arts", "label": "SH8 Studies of Cultures and Arts" }
                            ]
                        },
                        {
                            "name": "area_of_expertise_3",
                            "original_name": "input_51",
                            "label": "Area of expertise 3 (optional)",
                            "type": "select",
                            "required": false,
                            "options": [
                                { value: '', label: '' },
                                { "value": "PE1 Mathematics", "label": "PE1 Mathematics" },
                                { "value": "PE2 Fundamental Constituents of Matter", "label": "PE2 Fundamental Constituents of Matter" },
                                { "value": "PE3 Condensed Matter Physics", "label": "PE3 Condensed Matter Physics" },
                                { "value": "PE4 Physical and Analytical Chemical Sciences", "label": "PE4 Physical and Analytical Chemical Sciences" },
                                { "value": "PE5 Synthetic Chemistry and Materials", "label": "PE5 Synthetic Chemistry and Materials" },
                                { "value": "PE6 Computer Science and Informatics", "label": "PE6 Computer Science and Informatics" },
                                { "value": "PE7 Systems and Communication Engineering", "label": "PE7 Systems and Communication Engineering" },
                                { "value": "PE8 Products and Processes Engineering", "label": "PE8 Products and Processes Engineering" },
                                { "value": "PE9 Universe Sciences", "label": "PE9 Universe Sciences" },
                                { "value": "PE10 Earth System Science", "label": "PE10 Earth System Science" },
                                { "value": "PE11 Materials Engineering", "label": "PE11 Materials Engineering" },
                                { "value": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions", "label": "LS1 Molecules of Life: Biological Mechanisms, Structures and Functions" },
                                { "value": "LS2 Integrative Biology: from Genes and Genomes to Systems", "label": "LS2 Integrative Biology: from Genes and Genomes to Systems" },
                                { "value": "LS3 Cell Biology, Development, Stem Cells and Regeneration", "label": "LS3 Cell Biology, Development, Stem Cells and Regeneration" },
                                { "value": "LS4 Physiology in Health, Disease and Ageing", "label": "LS4 Physiology in Health, Disease and Ageing" },
                                { "value": "LS5 Neuroscience and Disorders of the Nervous System", "label": "LS5 Neuroscience and Disorders of the Nervous System" },
                                { "value": "LS6 Immunity, Infection and Immunotherapy", "label": "LS6 Immunity, Infection and Immunotherapy" },
                                { "value": "LS7 Prevention, Diagnosis and Treatment of Human Diseases", "label": "LS7 Prevention, Diagnosis and Treatment of Human Diseases" },
                                { "value": "LS8 Environmental Biology, Ecology and Evolution", "label": "LS8 Environmental Biology, Ecology and Evolution" },
                                { "value": "LS9 Biotechnology and Biosystems Engineering", "label": "LS9 Biotechnology and Biosystems Engineering" },
                                { "value": "SH1 Individuals, Markets and Organisations", "label": "SH1 Individuals, Markets and Organisations" },
                                { "value": "SH2 Institutions, Governance and Legal Systems", "label": "SH2 Institutions, Governance and Legal Systems" },
                                { "value": "SH3 The Social World and Its Interactions", "label": "SH3 The Social World and Its Interactions" },
                                { "value": "SH4 The Human Mind and Its Complexity", "label": "SH4 The Human Mind and Its Complexity" },
                                { "value": "SH5 Texts and Concepts", "label": "SH5 Texts and Concepts" },
                                { "value": "SH6 The Study of the Human Past", "label": "SH6 The Study of the Human Past" },
                                { "value": "SH7 Human Mobility, Environment, and Space", "label": "SH7 Human Mobility, Environment, and Space" },
                                { "value": "SH8 Studies of Cultures and Arts", "label": "SH8 Studies of Cultures and Arts" }
                            ]
                        },
                        {

                            name: 'experience_in_evaluating_eu_project',
                            label: 'Do you have experience in evaluating EU project proposals (Horizon Europe/Horizon 2020/FP7/FP6, ERC, MSCA, EIC, FET, etc.)?',
                            type: 'select',
                            required: true,
                            options: [
                                { value: '', label: '' },
                                { value: 'yes', label: 'Yes' },
                                { value: 'no', label: 'No' },
                            ]
                        },
                        {

                            name: 'how_did_you_hear_about_us',
                            label: 'How did you hear about our partner search?',
                            type: 'select',
                            required: true,
                            options: [
                                { value: '', label: '' },
                                { value: 'Internet search', label: 'Internet search' },
                                { value: 'Social media', label: 'Social media' },
                                { value: 'My institution has worked with you in the past', label: 'My institution has worked with you in the past' },
                                { value: 'I have worked with you in the past', label: 'I have worked with you in the past' },
                                { value: 'Recommendation from a colleague', label: 'Recommendation from a colleague' },
                                { value: 'Other', label: 'Other' },
                            ]
                        },
                        { name: 'subscribe_newsletter', label: 'Please subscribe me to the Enspire Science newsletter for insights, tips and guides about EU funding schemes 1', type: 'checkbox', required: true },
                        { name: 'agree_to_terms', label: 'I agree to all service terms as specified above', type: 'checkbox', required: true },
                        { name: 'agree_to_gdpr', label: 'GDPR: I consent to having Enspire Science collect my details, including my name and email address', type: 'checkbox', required: true },


                        // // Horizon Europe Alignment
                        // {
                        //     name: 'horizon_pillars',
                        //     label: 'Targeted Horizon Europe Pillars / Strategic Areas',
                        //     type: 'select',
                        //     required: true,
                        //     multiple: true,
                        //     options: [
                        //         { value: 'pillar_1_erc', label: 'Pillar I: ERC (European Research Council)' },
                        //         { value: 'pillar_1_msca', label: 'Pillar I: MSCA (Marie Skłodowska-Curie Actions)' },
                        //         { value: 'pillar_2_cluster_1', label: 'Pillar II: Cluster 1 - Health' },
                        //         { value: 'pillar_2_cluster_2', label: 'Pillar II: Cluster 2 - Culture, Creativity & Inclusive Society' },
                        //         { value: 'pillar_2_cluster_3', label: 'Pillar II: Cluster 3 - Civil Security for Society' },
                        //         { value: 'pillar_2_cluster_4', label: 'Pillar II: Cluster 4 - Digital, Industry & Space' },
                        //         { value: 'pillar_2_cluster_5', label: 'Pillar II: Cluster 5 - Climate, Energy & Mobility' },
                        //         { value: 'pillar_2_cluster_6', label: 'Pillar II: Cluster 6 - Food, Bioeconomy, Natural Resources, Agriculture & Environment' },
                        //         { value: 'pillar_3_eic', label: 'Pillar III: EIC (European Innovation Council)' }
                        //     ]
                        // },

                        // // Expertise & Matching Criteria
                        // { name: 'keywords', label: 'Keywords describing your research/expertise (comma-separated)', type: 'text', required: true },
                        // { name: 'expertise_summary', label: 'Core Expertise & Expected Contribution to a Consortium', type: 'textarea', required: true },
                        // { name: 'past_eu_experience', label: 'Describe past experience with EU-funded projects (H2020, Horizon Europe, FP7), if any', type: 'textarea', required: false },

                        // // Legal & Consent
                        // { name: 'newsletter', label: 'Subscribe to newsletter', type: 'checkbox', required: false, checkboxLabel: 'I want to receive updates, insights, and news regarding Horizon Europe from Enspire Science.' },
                        // { name: 'gdpr', label: 'GDPR Consent', type: 'checkbox', required: true, checkboxLabel: 'I consent to the processing and inclusion of my professional personal data in Enspire Science\'s Horizon Partner Search Database to receive tailored consortium matching opportunities.' }
                    ]}

            />
        </div>
    );
}